db = {
    "Masticophis flagellum": {
        "species": "Masticophis Flagellum",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Masticophis flagellum, commonly known as Coachwhips are thin-bodied snakes, with small heads and large eyes with round pupils.",
        "steps": "Will bite to defend. Don't try to chase snake off.",
        "bitten": "Bites by nonvenomous species require good wound care. Victims should get a tetanus booster if they have not had one within the last 5 years. These non-venomous snakes have needle-sharp teeth which produce lacerations when it bites, rather than punctures like fangs on venomous snakes do.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Masticophis_flagellum.jpg",
        "article": "https://en.wikipedia.org/wiki/Masticophis_flagellum"
    },
    "Crotalus atrox": {
        "species": "Crotalus Atrox",
        "type": "Snake",
        "poisonous": True,
        "cookable": False,
        "description": "Crotalus atrox, common known as the Western diamondback rattlesnakes, are non-aggressive venomous rattlesnakes. They are found in south-western parts of the US as well as Mexico. The Crotalus atrox are responsible for the greatest number of snakebites in the US.",
        "steps": "Best course of action is to not interfere with snake. Leave its surroundings immediately.Most rattlesnakes, when disturbed, normally try to withdraw, but if they think they are cornered, the explosive sizzling buzz of their rattle is an unmistakable warning to retreat and is a sound that will long be remembered.",
        "bitten": "The venom from the majority of rattlesnake bites will damage tissue and affect your circulatory system by destroying skin tissues and blood cells and by causing you to hemorrhage internally.  The first and most important thing to do is get away from the snake, as they can strike again if they feel threatened. SEEK MEDICAL ASSISTANCE IMMEDIATELY! Don't raise the area above the level of the heart. If you do this, your blood containing rattlesnake venom will reach your heart more quickly. Stay as still as possible, as movement will increase your blood flow and the venom will circulate faster. Remove any tight clothing or jewelry before you start to swell. Let the wound bleed, as this may allow some of the venom to be released. Don't wash the wound, as your medical team may be able to use some of the venom from your skin to more quickly identify the correct antivenin. Place a clean bandage on the wound. Try to remain calm, as anxiety and panic can increase your heart rate, which will cause the venom to spread. If you begin to experience signs of shock, try to lie down on your back, raise your feet slightly, and keep warm. Don't cut the wound, as this doesn't help and you could cause an infection. Don't try to suck the venom from the wound, as you then introduce the venom to your mouth as well as introduce the bacteria from your mouth to the wound. Don't use a tourniquet or apply ice or water. ",
        "image": "https://live.staticflickr.com/3870/14688594389_3cd92a0323_b.jpg",
        "article": "https://en.wikipedia.org/wiki/Western_diamondback_rattlesnake"
    },
    "Crotalus Oreganus": {
        "species": "Crotalus Oreganus",
        "type": "Snake",
        "poisonous": True,
        "cookable": False,
        "description": "Crotalus oreganus, commonly known as the Pacific rattlesnake, are non-aggressive venomous rattlesnakes. They are found in western North America, from southern California to as high as British Columbia.",
        "steps": "Best course of action is to not interfere with snake. Leave its surroundings immediately. Most rattlesnakes, when disturbed, normally try to withdraw, but if they think they are cornered, the explosive sizzling buzz of their rattle is an unmistakable warning to retreat and is a sound that will long be remembered.",
        "bitten": "The venom from the majority of rattlesnake bites will damage tissue and affect your circulatory system by destroying skin tissues and blood cells and by causing you to hemorrhage internally. The first and most important thing to do is get away from the snake, as they can strike again if they feel threatened. SEEK MEDICAL ASSISTANCE IMMEDIATELY! Don't raise the area above the level of the heart. If you do this, your blood containing rattlesnake venom will reach your heart more quickly. Stay as still as possible, as movement will increase your blood flow and the venom will circulate faster. Remove any tight clothing or jewelry before you start to swell. Let the wound bleed, as this may allow some of the venom to be released. Don't wash the wound, as your medical team may be able to use some of the venom from your skin to more quickly identify the correct antivenin. Place a clean bandage on the wound. Try to remain calm, as anxiety and panic can increase your heart rate, which will cause the venom to spread. If you begin to experience signs of shock, try to lie down on your back, raise your feet slightly, and keep warm. Don't cut the wound, as this doesn't help and you could cause an infection. Don't try to suck the venom from the wound, as you then introduce the venom to your mouth as well as introduce the bacteria from your mouth to the wound. Don't use a tourniquet or apply ice or water.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Crotalus_oreganus.jpg/220px-Crotalus_oreganus.jpg",
        "article": "https://en.wikipedia.org/wiki/Crotalus_oreganus"
    },
    "Pituophis catenifer": {
        "species": "Pituophis Catenifer",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Pituophis catenifers, or gopher snakes, are nonvenomous snakes commonly seen in California. Despite being nonvenomous and non-aggressive, their bites inflict a lot of pain and therefore should not be provoked.",
        "steps": "When it becomes afraid or agitated by humans, it will make itself look bigger and flatten its head. It even makes a rattling noise with its shaking tail, which is only heard in dry areas. Though it may look like it is about to cause as much harm as a rattlesnake, it can't u2013 this species is non-venomous and not poisonous. In fact, they are typically docile, and they pose no threat to humans (though the same can't be said for the small mammals they hunt). ",
        "bitten": "Bite can be very painful. However there is usually no long term damage. Make sure to clean wound using antiseptic. Check for dislodged snake tooth inside wound. If a gopher snake bites you, seek medical attention to ensure that the damage is no more than skin deep. ",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Pituophis_catenifer_catenifer_%28Carrizo_Plain%29.jpg/220px-Pituophis_catenifer_catenifer_%28Carrizo_Plain%29.jpg",
        "article": "https://a-z-animals.com/animals/gopher-snake/#single-animal-text"
    },
    "Lampropeltis getula californiae": {
        "species": "Lampropeltis Getula Californiae",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Lampropeltis getula californiae, or California kingsnakes are commonly found in western US. They are one of the most popular snakes due to their ease of care and variations in color.",
        "steps": "Kingsnakes are not known to be aggressive, and they will only bite when provoked. Often, kingsnakes bite when they feel threatened by a predator or an adversary. To avoid getting bitten by pet kingsnakes, you should observe their behavior. They may shake their tails and open their mouths while breathing to signal that they are uncomfortable. You may avoid handling them during these moments and just let them travel freely. ",
        "bitten": "Like most non-venomous snake bites, kingsnake bites can cause mild pain and swelling around the bite site. The bite wound may take some time to heal, but it wouldn't cause any further complications, so any person bitten by a kingsnake should not worry about any danger. ",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/California_Kingsnake_%28Lampropeltis_getula_californiae%29.JPG/220px-California_Kingsnake_%28Lampropeltis_getula_californiae%29.JPG",
        "article": "https://a-z-animals.com/blog/are-kingsnakes-poisonous-or-dangerous/"
    },
    "Coluber constrictor": {
        "species": "Coluber Constrictor",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Coluber constrictors, or eastern racers, are nonvenomous snakes generally found in Central and North America. Despite being nonvenomous, they will be aggressive if provoked, so proceed with caution.",
        "steps": "Eastern racers will not deliberately confront a human unless provoked. Nonvenomous but the bite may cause bleeding. They will bring no negative impact unless one attempts to handle or harass them. In which case, they will not hesitate to bite.",
        "bitten": "Bites from eastern racers may cause bleeding, but it is nonvenomous. May cause some pain and swelling but further complications are unlikely.",
        "image": "https://www. ps.gov/chis/learn/nature/images/960-2788698914_c262958545_o.jpg?maxwidth=650&autorotate=False",
        "article": "https://en.wikipedia.org/wiki/Eastern_racer"
    },
    "Diadophis punctatus": {
        "species": "Diadophis Punctatus",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Diadophis punctatus, commonly known as the ring-necked snake or ringneck snake, is a harmless species of colubrid snake found throughout much of the United States, central Mexico, and south-eastern Canada. Ring-necked snakes are secretive, nocturnal snakes, so are rarely seen during the day time. They are best known for their unique defense posture of curling up their tails, exposing their bright red-orange posterior, ventral surface when threatened.",
        "steps": "Ringneck snakes are not dangerous to humans. They very rarely bite. Prevention isn't neccesary as long as you don't threaten or hurt the snake.",
        "bitten": "Clean wound to avoid infection.They aren't be able to use their back fangs when they bite, so it doesn't hurt and will only leave a few bite marks. ",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Coral-belly_Ringneck_Snake_%28Diadophis_punctatus_ssp._pulchellus%29.jpg/220px-Coral-belly_Ringneck_Snake_%28Diadophis_punctatus_ssp._pulchellus%29.jpg",
        "article": "https://a-z-animals.com/blog/are-ringneck-snakes-poisonous-or-dangerous/"
    },
    "Thamnophis sauritus septentrionalis": {
        "species": "Thamnophis Sauritus Septentrionalis",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Thamnophis sauritus septentrionalis, commonly known as the northern ribbon snake, is a subspecies of garter snake found in the US and Canada. Their bites are likely to cause nothing more than a slight pinching sensation. They like attention and can be handled without too much worry.",
        "steps": "Eastern ribbon snakes are active and fast-moving snakes, most active during the day.  They are generally okay with being handled and their bite is not particularly dangerous, you will likely only feel a pinching sensation.",
        "bitten": "Bites from eastern ribbon snakes may hurt a little but are not harmful or venomous in any way. ",
        "image": "https://live.staticflickr.com/3702/10154493195_6ff2a0c852_b.jpg",
        "article": "https://a-z-animals.com/animals/ribbon-snake/#single-animal-text"
    },
    "Contia tenuis": {
        "species": "Contia Tenuis",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Contia tenuis, sharp-tailed snakes, are a small snake species found in western US.  Their bites are likely to cause nothing more than a slight pinching sensation.",
        "steps": "Sharp-tailed snakes are generally small and secretive. They will usually not harm you, but their bite is nothing to be worried about regardless.",
        "bitten": "Bites from sharp-tailed snakes may hurt a little but are not harmful or venomous in any way.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Contia_tenuis_%28San_Luis_Obispo%29.jpg/220px-Contia_tenuis_%28San_Luis_Obispo%29.jpg",
        "article": "https://a-z-animals.com/animals/sharp-tailed-snake/#single-animal-text"
    },
    "Charina bottae": {
        "species": "Charina Bottae",
        "type": "Snake",
        "poisonous": False,
        "cookable": False,
        "description": "Charina bottae, or the northern rubber boa, is a snake species native to North America. They are thick-bodied and slow-moving. They have simple care needs and do well with handling.",
        "steps": "Rubber boas are non-venomous. Though they have teeth, they are not aggressive snakes and unlikely to bite. Generally, they don't use their teeth as a defense.",
        "bitten": "If a bite does occur, the area should be thoroughly cleaned with soap and water. It's important to put first-aid ointment on the bite area in an effort to prevent infection. If the area becomes extremely red or a rash develops, it's a good idea to see a doctor.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Charina_bottae_on_towel.jpg/220px-Charina_bottae_on_towel.jpg",
        "article": "https://a-z-animals.com/animals/rubber-boa/#single-animal-text"
    },
    "Craterellus cornucopioides": {
        "species": "Craterellus Cornucopioides",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "Although it may sound deadly 'Trumpet of the dead' is actually an edible mushroom. However, legends say it breathes in your soul and uses it to play a trumpet that completely shatters your will to live :)!t",
        "steps": False,
        "bitten": "Can be eaten cooked (or raw as long as in small quantities).",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Craterellus_cornucopioides_JPG1.jpg/234px-Craterellus_cornucopioides_JPG1.jpg",
        "article": "https://en.wikipedia.org/wiki/Craterellus_cornucopioides"
    },
    "Sparassis radicata": {
        "species": "Sparassis Radicata",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "As its name suggests, the 'cauliflower fungus' has an appearance similar to cauliflower. They are easy to identify and can be found around the world. They make some pretty good meals as well, just make sure you clean them thoroughly.",
        "steps": False,
        "bitten": "Can be eaten cooked or raw.",
        "image": "https://www.mykoweb.com/CAF/photos/large/Sparassis_radicata%28bw_t5-073%29.jpg",
        "article": "https://en.wikipedia.org/wiki/Sparassis"
    },
    "Morchella rufobrunnea": {
        "species": "Morchella Rufobrunnea",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "The 'blushing morel' is a choice edible species found in southern North America, often described to have an 'earthy' taste. Like many other mushrooms, it should not be eaten raw.",
        "steps": False,
        "bitten": "Can be eaten cooked but should not be eaten raw.",
        "image": "https://s3-us-west-2.amazonaws.com/northernbushcraft.com/mushrooms/_blushing_morel/1.jpg",
        "article": "https://en.wikipedia.org/wiki/Morchella_rufobrunnea"
    },
    "Cantharellus formosus": {
        "species": "Cantharellus Formosus",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "The 'Pacific golden chanterelle' is one of the most popular wild edible mushrooms. It is native to the Pacific Northwest region of North America.",
        "steps": False,
        "bitten": "Can be eaten cooked or raw.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Cantharellus_formosus_174975_Belfair.jpg/1200px-Cantharellus_formosus_174975_Belfair.jpg",
        "article": "https://en.wikipedia.org/wiki/Cantharellus_formosus"
    },
    "Leccinum manzanitae": {
        "species": "Leccinum Manzanitae",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "Leccinum manzanitae is an edible species of mushroom found commonly in North America.",
        "steps": False,
        "bitten": "Can be eaten cooked or raw.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Leccinum_manzanitae_29496_crop.jpg",
        "article": "https://en.wikipedia.org/wiki/Leccinum_manzanitae"
    },
    "Agaricus bernardii": {
        "species": "Agaricus Bernardii",
        "type": "Mushroom",
        "poisonous": False,
        "cookable": True,
        "description": "Agaricus bernardii, commonly called the 'salt-loving mushroom,' is a short thick mushroom that is easy to identify, ",
        "steps": False,
        "bitten": "Can be eaten cooked but should not be eaten raw.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/5a/2011-12-02_Agaricus_bernardii_Qu%C3%A9l_187343.jpg",
        "article": "https://en.wikipedia.org/wiki/Agaricus_bernardii"
    },
    "Amanita phalloides": {
        "species": "Amanita Phalloides",
        "type": "Mushroom",
        "poisonous": True,
        "cookable": False,
        "description": "Amanita phalloides, the 'death cap,' is incredibly poisonous and causes the most deaths from foraged mushrooms worldwide.",
        "steps": False,
        "bitten": "CALL YOUR LOCAL POISON CENTER IMMEDIATELY! One death cap mushroom is normally enough to kill an adult but it is survivable if proper action is taken.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Amanita_phalloides_1.JPG/220px-Amanita_phalloides_1.JPG",
        "article": "Amanita phalloides - Wikipedia"
    },
    "Coprinopsis picacea": {
        "species": "Coprinopsis Picacea",
        "type": "Mushroom",
        "poisonous": True,
        "cookable": False,
        "description": "Coprinopsis picacea, magpie inkcap fungus, is a poisonous mushroom species, unlike many from the same genus.",
        "steps": False,
        "bitten": "The magpie inkcap is toxic and must not be eaten! If consumed, call your local poison center immediately and follow their guidance.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coprinopsis_picacea_12184.jpg/220px-Coprinopsis_picacea_12184.jpg",
        "article": "Coprinopsis picacea - Wikipedia"
    },
    "Amanita muscaria": {
        "species": "Amanita Muscaria",
        "type": "Mushroom",
        "poisonous": True,
        "cookable": True,
        "description": "Amanita muscaria, the 'fly agaric' is only cookable when following a certain procedure. It is safer to not use it for cooking unless with a professional, due to it being poisonous. They are found from southern Alaska all the way down to South America.",
        "steps": False,
        "bitten": "Cookable, but must be done properly else could have lethal effects. If you are not sure, it is better not to eat it!",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Amanita_muscaria_3_vliegenzwammen_op_rij.jpg/220px-Amanita_muscaria_3_vliegenzwammen_op_rij.jpg",
        "article": "Amanita muscaria - Wikipedia"
    },
    "Omphalotus olearius": {
        "species": "Omphalotus Olearius",
        "type": "Mushroom",
        "poisonous": True,
        "cookable": False,
        "description": "Omphalotus olearius, the 'jack-o'-lantern mushroom,' is a poisonous mushroom that may appear similar to chanterelles to the untrained eye. It has bioluminescent properties.",
        "steps": False,
        "bitten": "The jack-o'-lantern mushroom is poisonous and should not be eaten! While not lethal, it can lead to severe cramps, vomiting, and diarrhea. If consumed, call your local poison center for further guidance.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Omphalotus_olearus.png/220px-Omphalotus_olearus.png",
        "article": "Omphalotus olearius - Wikipedia"
    },
    "Micrurus fulvius": {
        "species": "Micrurus Fulvius",
        "type": "Snake",
        "poisonous": True,
        "cookable": False,
        "description": "Commonly known as coral snake, this slender, jewel-toned elapsid has bands of red, yellow, and black. It's also one of the most dangerous, as it produces a paralyzing neurotoxin.",
        "steps": "Coral snakes are very shy and unlikely to bite humans. Avoid handling and keep children away due to bright color. You should be safe around it even though it is so poisonous.",
        "bitten": "SEEK MEDICAL ASSISTANCE IMMEDIATELY! Call 911/ Poison hotline!. Even though the snake has probably administered a dry bite, you need medical care and antivenin right away. If you delay, you may experience double vision, slurred speech, and other signs that your nervous system is shutting down. Eventually, the nerves that control the muscles you breathe with will be paralyzed, and you will suffer respiratory failure and possibly die.",
        "image": "https://a-z-animals.com/media/2022/04/Eastern-Coral-Snake-on-the-ground.jpg",
        "article": "https://a-z-animals.com/animals/eastern-coral-snake/#single-animal-text"
    },
    "Agkistrodon contortrix": {
        "species": "Agkistrodon Contortrix",
        "type": "Snake",
        "poisonous": True,
        "cookable": False,
        "description": "Commonly known as Copperhead snake. This snake has a ground color is pale brown to pinkish-brown, and it has darker, hour-glass-shaped bands down its body.",
        "steps": "These snakes are not aggressive and can be described as shy. They have colors that help it camaflouge and most of the time it only bites when stepped on. ",
        "bitten": "SEEK MEDICAL ASSISTANCE IMMEDIATELY! Call 911/ Poison hotline!. Their bite may be painful but is very rarely fatal to humans.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Agkistrodon_contortrix_contortrix_CDC-a.png/220px-Agkistrodon_contortrix_contortrix_CDC-a.png",
        "article": "https://en.wikipedia.org/wiki/Eastern_copperhead"
    }
}